# Generated by Django 5.2.4 on 2026-06-24 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='skill',
            name='unique_skill_name_case_insensitive',
        ),
    ]
